#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fprintd
Version  : 0.8.0
Release  : 1
URL      : http://freedesktop.org/~hadess/fprintd-0.8.0.tar.xz
Source0  : http://freedesktop.org/~hadess/fprintd-0.8.0.tar.xz
Summary  : D-Bus service to access fingerprint readers
Group    : Development/Tools
License  : GPL-2.0
Requires: fprintd-bin = %{version}-%{release}
Requires: fprintd-data = %{version}-%{release}
Requires: fprintd-libexec = %{version}-%{release}
Requires: fprintd-license = %{version}-%{release}
Requires: fprintd-locales = %{version}-%{release}
Requires: fprintd-man = %{version}-%{release}
Requires: fprintd-services = %{version}-%{release}
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(libfprint)
BuildRequires : pkgconfig(polkit-gobject-1)
BuildRequires : pkgconfig(systemd)
BuildRequires : systemd-dev

%description
fprintd
=======
http://www.reactivated.net/fprint/wiki/Fprintd
Daemon to offer libfprint functionality over D-Bus
Might eat your kangaroo.

%package bin
Summary: bin components for the fprintd package.
Group: Binaries
Requires: fprintd-data = %{version}-%{release}
Requires: fprintd-libexec = %{version}-%{release}
Requires: fprintd-license = %{version}-%{release}
Requires: fprintd-services = %{version}-%{release}

%description bin
bin components for the fprintd package.


%package data
Summary: data components for the fprintd package.
Group: Data

%description data
data components for the fprintd package.


%package libexec
Summary: libexec components for the fprintd package.
Group: Default
Requires: fprintd-license = %{version}-%{release}

%description libexec
libexec components for the fprintd package.


%package license
Summary: license components for the fprintd package.
Group: Default

%description license
license components for the fprintd package.


%package locales
Summary: locales components for the fprintd package.
Group: Default

%description locales
locales components for the fprintd package.


%package man
Summary: man components for the fprintd package.
Group: Default

%description man
man components for the fprintd package.


%package services
Summary: services components for the fprintd package.
Group: Systemd services

%description services
services components for the fprintd package.


%prep
%setup -q -n fprintd-0.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557085868
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1557085868
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fprintd
cp COPYING %{buildroot}/usr/share/package-licenses/fprintd/COPYING
%make_install
%find_lang fprintd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fprintd-delete
/usr/bin/fprintd-enroll
/usr/bin/fprintd-list
/usr/bin/fprintd-verify

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/interfaces/net.reactivated.Fprint.Device.xml
/usr/share/dbus-1/interfaces/net.reactivated.Fprint.Manager.xml
/usr/share/dbus-1/system-services/net.reactivated.Fprint.service
/usr/share/dbus-1/system.d/net.reactivated.Fprint.conf
/usr/share/polkit-1/actions/net.reactivated.fprint.device.policy

%files libexec
%defattr(-,root,root,-)
/usr/libexec/fprintd

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fprintd/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/fprintd.1

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/fprintd.service

%files locales -f fprintd.lang
%defattr(-,root,root,-)

